"""Stage B + C of the Phase 2 crosswalk: generate candidate DMR-model -> DVSA-model
matches for the top N Danish models by fleet count, and emit crosswalk_review.csv
for human review. Nothing here is auto-accepted -- see phase2_crosswalk_strategy.md.

Two matching paths, chosen per-model, never mixed:
  - "code" path: DMR model normalizes to a short alphanumeric code (e.g. '320',
    'X5', '208', or 'C' after stripping '-Klasse') or a BMW-style family series
    ('3-Serie' etc). Only exact-code equality (or, for family series, the
    literal '{d} SERIES' string plus numeric siblings sharing that leading
    digit) is ever proposed. No similarity scoring touches these at all.
  - "name" path: everything else. DVSA candidates are generated by first-token
    collapse, scored by difflib.SequenceMatcher, and candidates that are
    themselves code-like are excluded from this path (a code should only ever
    be reached via exact match, never as a fuzzy neighbor of a name).
"""

from __future__ import annotations

import csv
import difflib
from collections import defaultdict
from pathlib import Path

import duckdb

from crosswalk_normalize import (
    family_series_digit,
    first_token,
    is_code_like,
    leading_code,
    normalize,
    strip_klasse_suffix,
    strip_ny_prefix,
)

ROOT = Path(__file__).resolve().parents[2]
WAREHOUSE = ROOT / "data" / "warehouse.duckdb"
ALIASES_CSV = ROOT / "pipeline" / "reference" / "make_aliases.csv"
REVIEW_CSV = ROOT / "pipeline" / "reference" / "crosswalk_review.csv"

TOP_N_MODELS = 214  # 90% fleet coverage target, confirmed by user
NAME_HIGH_THRESHOLD = 0.90
NAME_MEDIUM_THRESHOLD = 0.65

# Minimum UK test count for a match to be treated as real rather than a stray
# mis-keyed record. Set to the statistical-stability floor from the Phase 2
# strategy doc (n>=2000 gives under 1pp standard error on a ~0.75 pass rate),
# since a match too small to compute a stable metric from is not useful even
# if it is technically correct.
STABILITY_THRESHOLD = 2000

# Model-level renames researched directly (not discoverable by text similarity,
# since the strings share no characters) -- see phase2_crosswalk_strategy.md
# finding G. Seeded here rather than left as a bare no-candidate row, since the
# fact is already known and verified, not a guess for the reviewer to make.
KNOWN_MODEL_RENAMES = {
    ("OPEL", "KARL"): ("VAUXHALL", "VIVA", "Opel Karl is sold in the UK as the Vauxhall Viva; confirmed in Phase 2 strategy doc finding G."),
    # Added by the coverage_audit.md finding 2 fix. Without this, prefix_identity
    # fires on the literal DVSA make/model string "MITSUBISHI SPACE STAR" and
    # silently matches the wrong car: that DVSA pool is the 1998-2005 Space Star
    # MPV (first-use years cluster 2000-2005), not the Danish fleet's 2013-onward
    # car, which DVSA lists as "MIRAGE" (first-use years cluster 2013-2021,
    # matching exactly). See crosswalk_review.csv's decision_basis on this row.
    ("MITSUBISHI", "SPACE STAR"): ("MITSUBISHI", "MIRAGE", "Mitsubishi Space Star (Danish, 2013 on) is sold in the UK as the Mitsubishi Mirage. The DVSA make MITSUBISHI model SPACE STAR is a different, older car (1998-2005 MPV, first-use years cluster 2000-2005), confirmed by coverage_audit.md finding 2."),
}


def load_aliases() -> dict[str, str]:
    with open(ALIASES_CSV, encoding="utf-8") as f:
        return {row["dmr_make_name"]: row["dvsa_make"] for row in csv.DictReader(f)}


def build_dvsa_prefix_index(con: duckdb.DuckDBPyConnection, dvsa_make: str) -> dict[str, int]:
    """Token-PREFIX keyed test counts for one DVSA make.

    Every DVSA model string contributes its count to each of its leading token
    prefixes, so "CX 30 GT SPORT MHEV" adds to keys "CX", "CX 30",
    "CX 30 GT", ... This exists because first-token-only collapsing silently
    destroyed multi-token model names: Toyota's C-HR (190,836 tests) got filed
    under "C" and Mazda's CX-30 under "CX", making both unreachable, while
    also merging genuinely distinct models (CX-3 / CX-5 / CX-30) into one
    bucket.

    It also fixes the near-miss sibling problem for free, without any fuzzy
    scoring: "CORSAVAN" is a single token, so it never contributes to the
    "CORSA" key, and "AURIS" never contributes to "YARIS". Exact prefix
    matching separates them where similarity scoring could not.
    """
    rows = con.execute(
        "SELECT model, COUNT(*) c FROM mot_tests WHERE make = ? GROUP BY 1", [dvsa_make]
    ).fetchall()

    prefix_counts: dict[str, int] = defaultdict(int)
    for raw_model, count in rows:
        tokens = normalize(raw_model).split(" ")
        for i in range(1, len(tokens) + 1):
            prefix_counts[" ".join(tokens[:i])] += count
    return dict(prefix_counts)


def build_dvsa_index(con: duckdb.DuckDBPyConnection, dvsa_make: str):
    """Returns (code_counts, name_counts, family_series_counts) for one DVSA make.
    code_counts: {code -> summed test count} for short alphanumeric codes.
    name_counts: {first_token -> summed test count} for non-code-like tokens.
    family_series_counts: {family_digit -> ('{d} SERIES' literal test count)}.
    """
    rows = con.execute(
        "SELECT model, COUNT(*) c FROM mot_tests WHERE make = ? GROUP BY 1", [dvsa_make]
    ).fetchall()

    code_counts: dict[str, int] = defaultdict(int)
    name_counts: dict[str, int] = defaultdict(int)
    family_series_counts: dict[str, int] = defaultdict(int)

    for raw_model, count in rows:
        norm = normalize(raw_model)
        tok = first_token(norm)

        # literal "{digit} SERIES" must be checked before code extraction, since
        # the bare digit alone (e.g. "3") also satisfies is_code_like and would
        # otherwise get silently absorbed into code_counts["3"] -- which then
        # matches no downstream rule at all (family-sibling requires a second
        # digit) and the count is lost.
        if len(tok) == 1 and tok.isdigit() and norm == f"{tok} SERIES":
            family_series_counts[tok] += count
            continue

        code = leading_code(norm)
        if code is not None and is_code_like(tok):
            code_counts[code] += count
            continue

        if not is_code_like(tok):
            name_counts[tok] += count

    return code_counts, name_counts, family_series_counts


def dmr_probes(dmr_model_norm: str, dmr_make_norm: str) -> tuple[list[str], list[str]]:
    """Exact-match probe strings for one DMR model name, as (faithful, lossy).

    DMR writes the same car several ways and which form matches DVSA differs
    per make, so all plausible forms are tried rather than committing to one
    transformation up front.

    FAITHFUL probes still denote the whole model:
      - as-is ("CORSA")
      - make name stripped, whether glued ("MAZDA2" -> "2") or space-separated
        ("Toyota C-HR" -> "C HR")
      - de-spaced ("I 10" -> "I10", "DS 3" -> "DS3")
    Keeping and stripping the make prefix are both offered because either can
    be right: DVSA calls Toyota's crossover "C-HR" (prefix redundant) but calls
    DS's hatchback "DS3" (make name is genuinely part of the model name).

    LOSSY probes drop trailing tokens ("YARIS 5 DORS" -> "YARIS", "FABIA
    COMBI" -> "FABIA") to shed Danish body-style suffixes. They are tried only
    if no faithful probe lands, because truncation can silently widen a model
    into its whole family: "CX 30" truncates to "CX", which would merge CX-3,
    CX-5 and CX-30 into one bucket.

    Returned unsorted; the caller ranks hits by test volume, not by string
    length. Length ranking was tried first and picked tiny junk buckets over
    real models -- "Toyota C-HR" matched a 60-test "TOYOTA" prefix instead of
    the 190,836-test "C HR", and "MAZDA2" matched a 6-test "MAZDA2" instead of
    the 313,689-test "2", purely because the wrong string was longer.
    """
    # the Danish "Ny " ("new") prefix is dropped here, not only in the fuzzy
    # path, so "Ny Focus" can reach DVSA's "FOCUS" (2,291,752 tests) by exact
    # identity instead of arriving as a similarity guess alongside typo buckets
    # like "FOUCS" and "LOCUST".
    dmr_model_norm = strip_ny_prefix(dmr_model_norm)

    faithful: list[str] = [dmr_model_norm]

    if dmr_model_norm.startswith(dmr_make_norm) and len(dmr_model_norm) > len(dmr_make_norm):
        stripped = dmr_model_norm[len(dmr_make_norm):].strip()
        if stripped:
            faithful.append(stripped)

    for p in list(faithful):
        despaced = p.replace(" ", "")
        if despaced != p:
            faithful.append(despaced)

    lossy: list[str] = []
    tokens = dmr_model_norm.split(" ")
    for i in range(len(tokens) - 1, 0, -1):
        lossy.append(" ".join(tokens[:i]))

    def dedupe(xs):
        seen, out = set(), []
        for x in xs:
            if x and x not in seen:
                seen.add(x)
                out.append(x)
        return out

    faithful = dedupe(faithful)
    return faithful, [p for p in dedupe(lossy) if p not in set(faithful)]


def best_prefix_identity(
    dmr_model_norm: str, dmr_make_norm: str, prefix_counts: dict[str, int], threshold: int
) -> tuple[str, int] | None:
    """Best exact token-prefix hit for a DMR model, or None.

    Faithful probes are consulted before lossy ones, and within each group the
    highest-volume hit wins. Hits below `threshold` are skipped rather than
    accepted, because a match to a handful of tests is not evidence the model
    was found -- it is usually a stray mis-keyed DVSA record that happens to
    share the string. Kia's "CEE'D SW" is the worked example: it hits a 5-test
    "CEED SW" among the faithful probes, which must be passed over so the lossy
    "CEED" probe can reach the real 306,364-test model.
    """
    faithful, lossy = dmr_probes(dmr_model_norm, dmr_make_norm)

    # Faithful probes are alternative spellings of the SAME name, so the best
    # one is the highest-volume hit -- that is what skips junk buckets.
    #
    # Lossy probes are strictly nested truncations, so the best one is the
    # LONGEST that clears the floor, because a longer prefix is a more specific
    # claim. Ranking these by volume too was a real error: "Transit Custom
    # Kombi" truncates to both "TRANSIT CUSTOM" (147,808 tests, the actual
    # vehicle) and "TRANSIT" (734,085 tests, the larger unrelated van), and
    # volume ranking confidently picked the van.
    for group, key in ((faithful, lambda h: h[1]), (lossy, lambda h: len(h[0]))):
        hits = [(p, prefix_counts[p]) for p in group if p in prefix_counts]
        usable = [h for h in hits if h[1] >= threshold]
        if usable:
            return max(usable, key=key)

    # nothing clears the bar; surface the best sub-threshold hit anyway so the
    # row is visible and honestly flagged rather than silently absent.
    all_hits = [(p, prefix_counts[p]) for p in faithful + lossy if p in prefix_counts]
    return max(all_hits, key=lambda h: h[1]) if all_hits else None


def match_model(dmr_model_norm: str, dmr_make_norm: str, code_counts, name_counts, family_series_counts):
    """Returns a list of (dvsa_token, uk_count, confidence, rule_fired, match_score).

    match_score is 1.0 where the match is an identity or a structural fact (the
    normalized strings are literally equal, or the candidate is a numbered
    sibling of a resolved BMW-style family) and the actual string-similarity
    ratio where an inference was made. That distinction is what makes it
    possible to separate "no judgement was exercised here" from "a judgement
    was exercised here", which is exactly the line auto-confirmation must not
    cross.
    """
    candidates: list[tuple[str, int, str, str, float]] = []

    # strip the Danish "Ny " ("new") prefix before any classification, not just
    # inside the name-matching branch -- otherwise "Ny Clio" / "Ny Focus" never
    # even reach the name path to have it stripped (see is_code_like's docstring
    # for the related bug this compounds with).
    dmr_model_norm = strip_ny_prefix(dmr_model_norm)

    # DMR sometimes glues the make name onto the model as one word ("MAZDA2",
    # "MAZDA3" for what DVSA calls bare "2"/"3") -- verified: DVSA's real Mazda2
    # target is model "2" (291,935 tests), while "MAZDA2" fuzzy-matched a junk
    # "MAZDA" bucket (1,315 tests, mostly stray "MAZDA 2 HYBRID..." trims) before
    # this was stripped. Requires the make name to be glued directly to what
    # follows with NO space -- "DS 3" (DS brand's actual model name, a real
    # regression this caused on the first pass) has a space after "DS" and must
    # NOT be stripped down to bare "3", whereas "MAZDA2" has none.
    if (
        dmr_model_norm.startswith(dmr_make_norm)
        and len(dmr_model_norm) > len(dmr_make_norm)
        and dmr_model_norm[len(dmr_make_norm)] != " "
    ):
        dmr_model_norm = dmr_model_norm[len(dmr_make_norm):].strip()

    family_digit = family_series_digit(dmr_model_norm)
    if family_digit:
        if family_digit in family_series_counts:
            candidates.append(
                (f"{family_digit} SERIES", family_series_counts[family_digit], "high", "family_series_literal", 1.0)
            )
        prefix = family_digit
        for code, count in code_counts.items():
            if code[0] == prefix and code[1:2].isdigit():
                candidates.append((code, count, "high", "family_series_sibling", 1.0))
        return candidates

    # whole-string short alpha/alnum code: the ENTIRE model name (not just its
    # first word -- that distinction is what avoided the "NY"-as-code bug) is a
    # short token where a one-character difference is a different car: "CLA" vs
    # "GLA" vs "GLC" (Mercedes), "C" (post-Klasse-stripping). Verified "CLA"
    # fuzzy-matched "GLA" (ratio 0.667, above the medium threshold) before this
    # was added -- the exact same failure mode as 208/2008, just alphabetic.
    # Tries exact match first; if the exact target genuinely isn't in the DVSA
    # data at all, falls through to the normal fuzzy path rather than giving up,
    # since an absent exact target isn't evidence the model can't be matched.
    klasse_letter = strip_klasse_suffix(dmr_model_norm)
    whole_code = klasse_letter
    if whole_code is None and " " not in dmr_model_norm and dmr_model_norm.isalpha() and len(dmr_model_norm) <= 4:
        whole_code = dmr_model_norm
    if whole_code:
        if whole_code in code_counts:
            return [(whole_code, code_counts[whole_code], "exact", "short_code_exact", 1.0)]
        if whole_code in name_counts:
            return [(whole_code, name_counts[whole_code], "exact", "short_code_exact", 1.0)]
        # no exact target found -- fall through to numeric/name paths below

    dmr_code = leading_code(dmr_model_norm)
    dmr_is_code = dmr_code is not None and is_code_like(first_token(dmr_model_norm))

    if dmr_is_code and dmr_code:
        if dmr_code in code_counts:
            candidates.append((dmr_code, code_counts[dmr_code], "exact", "code_exact", 1.0))
        return candidates

    # name path: fuzzy, only against non-code DVSA tokens.
    #
    # DMR model names often carry a Danish body-style suffix the DVSA side
    # doesn't have ("FIESTA 5 DORS" = "Fiesta 5-door", "MONDEO STATIONCAR" =
    # "Mondeo estate"), which tanks the whole-string similarity score against
    # DVSA's already-collapsed single-word token even though the actual model
    # matches exactly once the suffix is dropped. So two comparisons are tried
    # per candidate -- whole normalized string, and DMR's own first token --
    # and the better-scoring one wins. Verified this recovers FIESTA, AYGO,
    # YARIS, MONDEO, FOCUS, MEGANE, ASTRA, FABIA, SX4, RAV4, and TRANSIT, all
    # of which were false no-candidate results before this was added.
    dmr_first_tok = first_token(dmr_model_norm)
    scored = []
    for tok, count in name_counts.items():
        ratio_full = difflib.SequenceMatcher(None, dmr_model_norm, tok).ratio()
        ratio_tok = difflib.SequenceMatcher(None, dmr_first_tok, tok).ratio()
        if ratio_tok >= ratio_full:
            ratio, rule = ratio_tok, "name_similarity_firsttoken"
        else:
            ratio, rule = ratio_full, "name_similarity_fullstring"
        scored.append((tok, count, ratio, rule))
    scored.sort(key=lambda x: (-x[2], -x[1]))

    for tok, count, ratio, rule in scored[:5]:
        if ratio >= NAME_HIGH_THRESHOLD:
            candidates.append((tok, count, "high", rule, ratio))
        elif ratio >= NAME_MEDIUM_THRESHOLD:
            candidates.append((tok, count, "medium", rule, ratio))
    return candidates


def main() -> None:
    aliases = load_aliases()
    con = duckdb.connect(str(WAREHOUSE), read_only=True)

    dmr_models = con.execute(
        """
        SELECT make_id, make_name, model_id, model_name, vehicle_count
        FROM top_models_by_id
        ORDER BY vehicle_count DESC
        LIMIT ?
        """,
        [TOP_N_MODELS],
    ).fetchall()

    dvsa_index_cache: dict[str, tuple] = {}
    dvsa_prefix_cache: dict[str, dict[str, int]] = {}

    out_rows = []
    for make_id, make_name, model_id, model_name, dk_count in dmr_models:
        variants = con.execute(
            """
            SELECT variant_name FROM dk_fleet
            WHERE make_id = ? AND model_id = ?
            ORDER BY vehicle_count DESC LIMIT 3
            """,
            [make_id, model_id],
        ).fetchall()
        sample_variants = "; ".join(v[0] for v in variants if v[0])

        dvsa_make = aliases.get(make_name)
        if not dvsa_make:
            out_rows.append(
                dict(
                    dmr_make_id=make_id, dmr_model_id=model_id,
                    dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                    dk_sample_variants=sample_variants, proposed_dvsa_make="",
                    proposed_dvsa_model_token="", uk_test_count=0,
                    confidence="no-make-mapping", rule_fired="", match_score="",
                    decision="", decision_basis="",
                )
            )
            continue

        known = KNOWN_MODEL_RENAMES.get((make_name, normalize(model_name)))
        if known:
            known_make, known_token, basis = known
            known_count = con.execute(
                "SELECT COUNT(*) FROM mot_tests WHERE make = ? AND split_part(model, ' ', 1) = ?",
                [known_make, known_token],
            ).fetchone()[0]
            out_rows.append(
                dict(
                    dmr_make_id=make_id, dmr_model_id=model_id,
                    dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                    dk_sample_variants=sample_variants, proposed_dvsa_make=known_make,
                    proposed_dvsa_model_token=known_token, uk_test_count=known_count,
                    confidence="known-rename", rule_fired=basis, match_score=1.0,
                    decision="", decision_basis="",
                )
            )
            continue

        if dvsa_make not in dvsa_index_cache:
            dvsa_index_cache[dvsa_make] = build_dvsa_index(con, dvsa_make)
        code_counts, name_counts, family_series_counts = dvsa_index_cache[dvsa_make]
        if dvsa_make not in dvsa_prefix_cache:
            dvsa_prefix_cache[dvsa_make] = build_dvsa_prefix_index(con, dvsa_make)
        prefix_counts = dvsa_prefix_cache[dvsa_make]

        dmr_norm = normalize(model_name)
        make_norm = normalize(make_name)

        # Exact token-prefix identity is tried before anything else: if some
        # form of the DMR model name IS literally a DVSA model-name prefix,
        # no inference is being made and no similarity scoring should get a say.
        identity_hit = best_prefix_identity(dmr_norm, make_norm, prefix_counts, STABILITY_THRESHOLD)

        if identity_hit and not family_series_digit(strip_ny_prefix(dmr_norm)):
            tok, count = identity_hit
            candidates = [(tok, count, "exact", "prefix_identity", 1.0)]
        else:
            candidates = match_model(dmr_norm, make_norm, code_counts, name_counts, family_series_counts)

        if not candidates:
            out_rows.append(
                dict(
                    dmr_make_id=make_id, dmr_model_id=model_id,
                    dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                    dk_sample_variants=sample_variants, proposed_dvsa_make=dvsa_make,
                    proposed_dvsa_model_token="", uk_test_count=0,
                    confidence="no-candidate", rule_fired="", match_score="",
                    decision="", decision_basis="",
                )
            )
        else:
            seen_tokens = set()
            for tok, count, confidence, rule, score in sorted(candidates, key=lambda c: -c[1]):
                if tok in seen_tokens:
                    continue
                seen_tokens.add(tok)
                out_rows.append(
                    dict(
                        dmr_make_id=make_id, dmr_model_id=model_id,
                        dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                        dk_sample_variants=sample_variants, proposed_dvsa_make=dvsa_make,
                        proposed_dvsa_model_token=tok, uk_test_count=count,
                        confidence=confidence, rule_fired=rule, match_score=round(score, 4),
                        decision="", decision_basis="",
                    )
                )

    ALIASES_CSV.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "dmr_make_id", "dmr_model_id",
        "dmr_make", "dmr_model", "dk_vehicle_count", "dk_sample_variants",
        "proposed_dvsa_make", "proposed_dvsa_model_token", "uk_test_count",
        "confidence", "rule_fired", "match_score", "decision", "decision_basis",
    ]
    with open(REVIEW_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(out_rows)

    n_models = len(dmr_models)
    n_rows = len(out_rows)
    n_no_candidate = sum(1 for r in out_rows if r["confidence"] == "no-candidate")
    n_exact = sum(1 for r in out_rows if r["confidence"] == "exact")
    print(f"models processed: {n_models}")
    print(f"review rows written: {n_rows}")
    print(f"  exact: {n_exact}")
    print(f"  no-candidate (need manual lookup): {n_no_candidate}")
    print(f"wrote {REVIEW_CSV}")


if __name__ == "__main__":
    main()
