"""Stage B + C of the Phase 2 crosswalk: generate candidate DMR-model -> DVSA-model
matches for the top N Danish models by fleet count, and emit crosswalk_review.csv
for human review. Nothing here is auto-accepted -- see phase2_crosswalk_strategy.md.

Two matching paths, chosen per-model, never mixed:
  - "code" path: DMR model normalizes to a short alphanumeric code (e.g. '320',
    'X5', '208', or 'C' after stripping '-Klasse') or a BMW-style family series
    ('3-Serie' etc). Only exact-code equality (or, for family series, the
    literal '{d} SERIES' string plus numeric siblings sharing that leading
    digit) is ever proposed. No similarity scoring touches these at all.
  - "name" path: everything else. DVSA candidates are generated by first-token
    collapse, scored by difflib.SequenceMatcher, and candidates that are
    themselves code-like are excluded from this path (a code should only ever
    be reached via exact match, never as a fuzzy neighbor of a name).
"""

from __future__ import annotations

import csv
import difflib
from collections import defaultdict
from pathlib import Path

import duckdb

from crosswalk_normalize import (
    family_series_digit,
    first_token,
    is_code_like,
    leading_code,
    normalize,
    strip_klasse_suffix,
    strip_ny_prefix,
)

ROOT = Path(__file__).resolve().parents[2]
WAREHOUSE = ROOT / "data" / "warehouse.duckdb"
ALIASES_CSV = ROOT / "pipeline" / "reference" / "make_aliases.csv"
REVIEW_CSV = ROOT / "pipeline" / "reference" / "crosswalk_review.csv"

TOP_N_MODELS = 214  # 90% fleet coverage target, confirmed by user
NAME_HIGH_THRESHOLD = 0.90
NAME_MEDIUM_THRESHOLD = 0.65

# Model-level renames researched directly (not discoverable by text similarity,
# since the strings share no characters) -- see phase2_crosswalk_strategy.md
# finding G. Seeded here rather than left as a bare no-candidate row, since the
# fact is already known and verified, not a guess for the reviewer to make.
KNOWN_MODEL_RENAMES = {
    ("OPEL", "KARL"): ("VAUXHALL", "VIVA", "Opel Karl is sold in the UK as the Vauxhall Viva; confirmed in Phase 2 strategy doc finding G."),
}


def load_aliases() -> dict[str, str]:
    with open(ALIASES_CSV, encoding="utf-8") as f:
        return {row["dmr_make_name"]: row["dvsa_make"] for row in csv.DictReader(f)}


def build_dvsa_index(con: duckdb.DuckDBPyConnection, dvsa_make: str):
    """Returns (code_counts, name_counts, family_series_counts) for one DVSA make.
    code_counts: {code -> summed test count} for short alphanumeric codes.
    name_counts: {first_token -> summed test count} for non-code-like tokens.
    family_series_counts: {family_digit -> ('{d} SERIES' literal test count)}.
    """
    rows = con.execute(
        "SELECT model, COUNT(*) c FROM mot_tests WHERE make = ? GROUP BY 1", [dvsa_make]
    ).fetchall()

    code_counts: dict[str, int] = defaultdict(int)
    name_counts: dict[str, int] = defaultdict(int)
    family_series_counts: dict[str, int] = defaultdict(int)

    for raw_model, count in rows:
        norm = normalize(raw_model)
        tok = first_token(norm)

        # literal "{digit} SERIES" must be checked before code extraction, since
        # the bare digit alone (e.g. "3") also satisfies is_code_like and would
        # otherwise get silently absorbed into code_counts["3"] -- which then
        # matches no downstream rule at all (family-sibling requires a second
        # digit) and the count is lost.
        if len(tok) == 1 and tok.isdigit() and norm == f"{tok} SERIES":
            family_series_counts[tok] += count
            continue

        code = leading_code(norm)
        if code is not None and is_code_like(tok):
            code_counts[code] += count
            continue

        if not is_code_like(tok):
            name_counts[tok] += count

    return code_counts, name_counts, family_series_counts


def match_model(dmr_model_norm: str, dmr_make_norm: str, code_counts, name_counts, family_series_counts):
    """Returns a list of (dvsa_token, uk_count, confidence, rule_fired)."""
    candidates: list[tuple[str, int, str, str]] = []

    # strip the Danish "Ny " ("new") prefix before any classification, not just
    # inside the name-matching branch -- otherwise "Ny Clio" / "Ny Focus" never
    # even reach the name path to have it stripped (see is_code_like's docstring
    # for the related bug this compounds with).
    dmr_model_norm = strip_ny_prefix(dmr_model_norm)

    # DMR sometimes glues the make name onto the model as one word ("MAZDA2",
    # "MAZDA3" for what DVSA calls bare "2"/"3") -- verified: DVSA's real Mazda2
    # target is model "2" (291,935 tests), while "MAZDA2" fuzzy-matched a junk
    # "MAZDA" bucket (1,315 tests, mostly stray "MAZDA 2 HYBRID..." trims) before
    # this was stripped. Requires the make name to be glued directly to what
    # follows with NO space -- "DS 3" (DS brand's actual model name, a real
    # regression this caused on the first pass) has a space after "DS" and must
    # NOT be stripped down to bare "3", whereas "MAZDA2" has none.
    if (
        dmr_model_norm.startswith(dmr_make_norm)
        and len(dmr_model_norm) > len(dmr_make_norm)
        and dmr_model_norm[len(dmr_make_norm)] != " "
    ):
        dmr_model_norm = dmr_model_norm[len(dmr_make_norm):].strip()

    family_digit = family_series_digit(dmr_model_norm)
    if family_digit:
        if family_digit in family_series_counts:
            candidates.append(
                (f"{family_digit} SERIES", family_series_counts[family_digit], "high", "family_series_literal")
            )
        prefix = family_digit
        for code, count in code_counts.items():
            if code[0] == prefix and code[1:2].isdigit():
                candidates.append((code, count, "high", "family_series_sibling"))
        return candidates

    # whole-string short alpha/alnum code: the ENTIRE model name (not just its
    # first word -- that distinction is what avoided the "NY"-as-code bug) is a
    # short token where a one-character difference is a different car: "CLA" vs
    # "GLA" vs "GLC" (Mercedes), "C" (post-Klasse-stripping). Verified "CLA"
    # fuzzy-matched "GLA" (ratio 0.667, above the medium threshold) before this
    # was added -- the exact same failure mode as 208/2008, just alphabetic.
    # Tries exact match first; if the exact target genuinely isn't in the DVSA
    # data at all, falls through to the normal fuzzy path rather than giving up,
    # since an absent exact target isn't evidence the model can't be matched.
    klasse_letter = strip_klasse_suffix(dmr_model_norm)
    whole_code = klasse_letter
    if whole_code is None and " " not in dmr_model_norm and dmr_model_norm.isalpha() and len(dmr_model_norm) <= 4:
        whole_code = dmr_model_norm
    if whole_code:
        if whole_code in code_counts:
            return [(whole_code, code_counts[whole_code], "exact", "short_code_exact")]
        if whole_code in name_counts:
            return [(whole_code, name_counts[whole_code], "exact", "short_code_exact")]
        # no exact target found -- fall through to numeric/name paths below

    dmr_code = leading_code(dmr_model_norm)
    dmr_is_code = dmr_code is not None and is_code_like(first_token(dmr_model_norm))

    if dmr_is_code and dmr_code:
        if dmr_code in code_counts:
            candidates.append((dmr_code, code_counts[dmr_code], "exact", "code_exact"))
        return candidates

    # name path: fuzzy, only against non-code DVSA tokens.
    #
    # DMR model names often carry a Danish body-style suffix the DVSA side
    # doesn't have ("FIESTA 5 DORS" = "Fiesta 5-door", "MONDEO STATIONCAR" =
    # "Mondeo estate"), which tanks the whole-string similarity score against
    # DVSA's already-collapsed single-word token even though the actual model
    # matches exactly once the suffix is dropped. So two comparisons are tried
    # per candidate -- whole normalized string, and DMR's own first token --
    # and the better-scoring one wins. Verified this recovers FIESTA, AYGO,
    # YARIS, MONDEO, FOCUS, MEGANE, ASTRA, FABIA, SX4, RAV4, and TRANSIT, all
    # of which were false no-candidate results before this was added.
    dmr_first_tok = first_token(dmr_model_norm)
    scored = []
    for tok, count in name_counts.items():
        ratio_full = difflib.SequenceMatcher(None, dmr_model_norm, tok).ratio()
        ratio_tok = difflib.SequenceMatcher(None, dmr_first_tok, tok).ratio()
        if ratio_tok >= ratio_full:
            ratio, rule = ratio_tok, "name_similarity_firsttoken"
        else:
            ratio, rule = ratio_full, "name_similarity_fullstring"
        scored.append((tok, count, ratio, rule))
    scored.sort(key=lambda x: (-x[2], -x[1]))

    for tok, count, ratio, rule in scored[:5]:
        if ratio >= NAME_HIGH_THRESHOLD:
            candidates.append((tok, count, "high", rule))
        elif ratio >= NAME_MEDIUM_THRESHOLD:
            candidates.append((tok, count, "medium", rule))
    return candidates


def main() -> None:
    aliases = load_aliases()
    con = duckdb.connect(str(WAREHOUSE), read_only=True)

    dmr_models = con.execute(
        """
        SELECT make_id, make_name, model_id, model_name, vehicle_count
        FROM top_models_by_id
        ORDER BY vehicle_count DESC
        LIMIT ?
        """,
        [TOP_N_MODELS],
    ).fetchall()

    dvsa_index_cache: dict[str, tuple] = {}

    out_rows = []
    for make_id, make_name, model_id, model_name, dk_count in dmr_models:
        variants = con.execute(
            """
            SELECT variant_name FROM dk_fleet
            WHERE make_id = ? AND model_id = ?
            ORDER BY vehicle_count DESC LIMIT 3
            """,
            [make_id, model_id],
        ).fetchall()
        sample_variants = "; ".join(v[0] for v in variants if v[0])

        dvsa_make = aliases.get(make_name)
        if not dvsa_make:
            out_rows.append(
                dict(
                    dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                    dk_sample_variants=sample_variants, proposed_dvsa_make="",
                    proposed_dvsa_model_token="", uk_test_count=0,
                    confidence="no-make-mapping", rule_fired="", decision="",
                )
            )
            continue

        known = KNOWN_MODEL_RENAMES.get((make_name, normalize(model_name)))
        if known:
            known_make, known_token, basis = known
            known_count = con.execute(
                "SELECT COUNT(*) FROM mot_tests WHERE make = ? AND split_part(model, ' ', 1) = ?",
                [known_make, known_token],
            ).fetchone()[0]
            out_rows.append(
                dict(
                    dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                    dk_sample_variants=sample_variants, proposed_dvsa_make=known_make,
                    proposed_dvsa_model_token=known_token, uk_test_count=known_count,
                    confidence="known-rename", rule_fired=basis, decision="",
                )
            )
            continue

        if dvsa_make not in dvsa_index_cache:
            dvsa_index_cache[dvsa_make] = build_dvsa_index(con, dvsa_make)
        code_counts, name_counts, family_series_counts = dvsa_index_cache[dvsa_make]

        dmr_norm = normalize(model_name)
        candidates = match_model(dmr_norm, normalize(make_name), code_counts, name_counts, family_series_counts)

        if not candidates:
            out_rows.append(
                dict(
                    dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                    dk_sample_variants=sample_variants, proposed_dvsa_make=dvsa_make,
                    proposed_dvsa_model_token="", uk_test_count=0,
                    confidence="no-candidate", rule_fired="", decision="",
                )
            )
        else:
            seen_tokens = set()
            for tok, count, confidence, rule in sorted(candidates, key=lambda c: -c[1]):
                if tok in seen_tokens:
                    continue
                seen_tokens.add(tok)
                out_rows.append(
                    dict(
                        dmr_make=make_name, dmr_model=model_name, dk_vehicle_count=dk_count,
                        dk_sample_variants=sample_variants, proposed_dvsa_make=dvsa_make,
                        proposed_dvsa_model_token=tok, uk_test_count=count,
                        confidence=confidence, rule_fired=rule, decision="",
                    )
                )

    ALIASES_CSV.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "dmr_make", "dmr_model", "dk_vehicle_count", "dk_sample_variants",
        "proposed_dvsa_make", "proposed_dvsa_model_token", "uk_test_count",
        "confidence", "rule_fired", "decision",
    ]
    with open(REVIEW_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(out_rows)

    n_models = len(dmr_models)
    n_rows = len(out_rows)
    n_no_candidate = sum(1 for r in out_rows if r["confidence"] == "no-candidate")
    n_exact = sum(1 for r in out_rows if r["confidence"] == "exact")
    print(f"models processed: {n_models}")
    print(f"review rows written: {n_rows}")
    print(f"  exact: {n_exact}")
    print(f"  no-candidate (need manual lookup): {n_no_candidate}")
    print(f"wrote {REVIEW_CSV}")


if __name__ == "__main__":
    main()
